version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
  
    steps:
      - checkout
      
      - run:
          name: "Install"
          command: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
      
      - run:
          name: "Install"
          command: dpkg -i packages-microsoft-prod.deb
       
      - run:
          name: "Install"
          command: apt-get update
          
      - run:
          name: "Install"
          command: apt-get install dotnet-sdk-3.0 sudo
          
      - run:
          name: "Run the app"
          command: dotnet bin/Debug/netcoreapp3.0/circleCI.dll
