version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
  
    steps:
      - checkout
            
      - run:
          name: "Run the app"
          command: dotnet run
          working_directory: circleCI
