version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
  
    steps:
      - checkout

      - run:
          name: "Run the app"
          command: dotnet bin/Debug/netcoreapp3.0/circleCI.dll
