version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
  
    steps:
      - checkout
      
      - run:
          name: "Install"
          command: apt-get update
          
      - run:
          name: "Install"
          command: apt-get install dotnet-sdk-2.2
          
      - run:
          name: "Run the app"
          command: dotnet bin/Debug/netcoreapp3.0/circleCI.dll
