version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
  
    steps:
      - checkout

      - run:
          name: "Test the executable"
          command: .\bin\Release\netcoreapp3.0\win10-x64\publish\CircleCI.exe

      - store_artifacts:
          path: .\bin\Release\netcoreapp3.0\win10-x64\publish\CircleCI.exe
